apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-ingress-contoso-com-tls-secret-csi-akv
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data:
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.key
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.crt
  parameters:
    clientID: 277969fb-bec3-4471-b6d4-1b5f49d6dd1b
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: kv-aks-ss665chnplohw
    objects: |
      array:
        - |
          objectName: ingress-internal-aks-ingress-contoso-com-tls
          objectType: secret
    tenantID: 
